name: RandomItem
main: LDX\RandomItem\Main
version: 4.2
api: [1.0.0,1.1.0,1.2.0,1.3.0,1.4.0]
author: LDX
load: POSTWORLD
commands:
  gift:
    permission: randomitem.gift
    description: Gives a random item
    usage: /gift [player]
permissions:
  randomitem:
    description: Allows access to all RandomItem features.
    default: false
    children:
      randomitem.gift:
        description: Allows players to use the gift command.
        default: op
      randomitem.ontimer:
        description: Allows players to recieve an item when a timed item is given.
        default: true
      randomitem.ongift:
        description: Allows players to recieve an item when the gift command is used.
        default: true
      randomitem.onkill:
        description: Allows players to recieve an item when they kill another player.
        default: true
