name: RandomItem
main: LDX\RandomItem\Main
version: 4.1
api: [1.0.0,1.1.0,1.2.0,1.3.0,1.4.0]
author: LDX
load: POSTWORLD
commands:
  gift:
    permission: randomitem.gift
    description: Gives a random item
    usage: /gift [player]
permissions:
  randomitem.gift:
    description: Allows players to use the gift command
    default: op
