name: RandomItem
main: LDX\RandomItem\Main
version: 4.3
api: 3.0.0
author: LDX
load: POSTWORLD
website: https://github.com/LDX-MCPE/RandomItem
commands:
  gift:
    permission: randomitem.gift
    description: Gives a random item
    usage: /gift [player]
permissions:
  randomitem:
    description: Allows access to all RandomItem features.
    default: false
    children:
      randomitem.gift:
        description: Allows players to use the gift command.
        default: op
      randomitem.receive:
        description: Allows players to receive random items.
        default: true
